# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
# disable hydra-colorlog as https://github.com/ashleve/lightning-hydra-template/issues/528

# defaults:
# - override hydra_logging: colorlog
# - override job_logging: colorlog

# output directory, generated dynamically on each run
run:
  dir: ${paths.log_dir}/${task_name}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
sweep:
  dir: ${paths.log_dir}/${task_name}/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
  subdir: ${hydra.job.num}
job:
  chdir: True
