batch_inference_step:
  _target_: src.models.callbacks.batch_inference_step.BatchInferenceStepCallback
  extract_phases: ["P", "S"]
  model_phases: ["P", "S", "PS"]
  extract_phase_sensitivity: [0.5, 0.5]
  dt_s: 0.025
  window_length_in_npts: 4800
  hop_length_in_npts: 2400
  sensitive_distances_in_seconds: 5.0
