name: Build Docker Image

on:
  push:
    branches:
      - main # Set the branch that triggers the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/phasenet-tf:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/phasenet-tf:latest
